"use client";
import { useMemo, useState } from "react";

const courses = [
  ["30-Day SAP Interview Mastery Intensive","Already Trained","4 intensive weeks"],["SAP BW/4HANA","Beginner to Advanced","28 lessons"],["SAP Datasphere","Beginner","24 lessons"],["SAP Analytics Cloud","Intermediate","22 lessons"],["SAC Planning","Intermediate","20 lessons"],["SAP Business Data Cloud (BDC)","Intermediate","18 lessons"],["SAP Business Technology Platform (BTP)","Beginner","26 lessons"],["Business Data Modeling","Beginner","24 lessons"],["Data & Replication Flows","Intermediate","20 lessons"],["Security & Data Access","Advanced","14 lessons"],["End-to-End Data Product","Capstone","8 workshops"]
];
const categories=["All Courses","SAP BW/4HANA","SAP Datasphere","SAP Analytics Cloud","SAC Planning","Business Data Cloud","SAP BTP"];

export default function Home(){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All Courses"); const [more,setMore]=useState(false); const [course,setCourse]=useState<string|null>(null); const [sent,setSent]=useState(false);
 const filtered=useMemo(()=>courses.filter(c=>(c.join(" ").toLowerCase().includes(query.toLowerCase()))&&(category==="All Courses"||c[0].toLowerCase().includes(category.replace("SAP ","").toLowerCase()))),[query,category]);
 const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
 return <main>
  <div className="notice">Admissions open for the next SAP Data Analytics cohort <button onClick={()=>go("courses")}>Explore courses →</button></div>
  <header><a className="logo" href="#home"><b>DF</b><span>DataForge<small>SAP DATA ACADEMY</small></span></a><nav>{[["Home","home"],["Courses","courses"],["Benefits","benefits"],["Faculty","faculty"],["Contact","contact"]].map(([x,id])=><button onClick={()=>go(id)} key={x}>{x}</button>)}</nav><button className="login">Student Login</button></header>
  <section className="hero" id="home"><div><span className="pill">LIVE · PROJECT-LED · CAREER-FOCUSED</span><h1>Build Better <em>SAP Data Skills.</em></h1><p>Master SAP Datasphere and Analytics Cloud through guided classes, practical labs, and portfolio-ready projects.</p><label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search SAP courses..."/><button onClick={()=>go("courses")}>Search</button></label><small>Join an active community of early-career data engineers.</small></div></section>
  <section className="logos"><h2>Skills designed for the modern data ecosystem</h2><div className="logo-run right"><p>{[...Array(2)].flatMap(()=>["SAP","DATASPHERE","S/4HANA","ANALYTICS CLOUD","SQL","POWER BI"]).map((x,i)=><b key={i}>{x}</b>)}</p></div><div className="logo-run left"><p>{[...Array(2)].flatMap(()=>["ACCENTURE","DELOITTE","CAPGEMINI","INFOSYS","WIPRO","GENPACT"]).map((x,i)=><b key={i}>{x}</b>)}</p></div></section>
  <section className="catalog" id="courses"><h2>Explore Our All Courses</h2><div className="catalog-layout"><aside>{categories.map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</aside><div className="cards">{filtered.slice(0,more?filtered.length:6).map((c,i)=><article key={c[0]}><div className={`cover c${i%4}`}><span>DF ACADEMY</span><strong>{c[0]}</strong></div><h3>{c[0]}</h3><p><span>{c[1]}</span><span>{c[2]}</span></p><button onClick={()=>setCourse(c[0])}>View Program</button></article>)}</div></div>{filtered.length>6&&<button className="show" onClick={()=>setMore(!more)}>{more?"Show less":"Show more"} →</button>}</section>
  <section className="intensive"><div className="intensive-intro"><span>FOR ALREADY-TRAINED CANDIDATES</span><h2>30-Day SAP Interview<br/>Mastery Intensive</h2><p>Learn how to answer confidently—not just what to know. Build a memorable self-introduction, explain projects at the right depth, handle technical follow-ups, and improve through repeated mock interviews.</p><button onClick={()=>setCourse("30-Day SAP Interview Mastery Intensive")}>View intensive program →</button></div><div className="weeks">{[
    ["WEEK 01","Self-Introduction & Personal Positioning","Create 30-second, 60-second, and 2-minute introductions. Connect your education, experience, SAP training, strongest skills, projects, career transition, strengths, and target role without sounding memorized."],
    ["WEEK 02","Answer Project Questions with Structure","Use a clear flow: business problem, landscape, architecture, your responsibility, implementation, challenges, and outcome. Practise short, medium, and deep versions."],
    ["WEEK 03","Technical, Scenario & Follow-up Questions","Answer with context, assumptions, approach, decision, and result. Practise why, what-if, troubleshooting, comparison, performance, and production-support questions without bluffing."],
    ["WEEK 04","Repeated Mock Interviews & Final Readiness","Complete HR, technical, project-manager, and panel mock rounds. Improve clarity, confidence, listening, pace, body language, filler words, answer depth, and recovery when you do not know."],
  ].map(([week,title,copy])=><article key={week}><b>{week}</b><h3>{title}</h3><p>{copy}</p><span>Practice and feedback every week ✓</span></article>)}</div><div className="answer-framework"><h3>A simple framework for strong interview answers</h3><div>{[["01 · LISTEN","Understand the exact question and clarify scope when needed."],["02 · STRUCTURE","Give the direct answer, then context, approach, example, and result."],["03 · PROVE","Use specific decisions, challenges, numbers, and your contribution."],["04 · CLOSE","Summarize the outcome and pause instead of over-explaining."]].map(([title,copy])=><article key={title}><b>{title}</b><p>{copy}</p></article>)}</div></div><div className="intensive-outcomes"><h3>Every candidate leaves with</h3><div>{["3 polished self-introductions","Primary and backup project stories","50+ rehearsed interview answers","10+ STAR challenge stories","HR and salary-answer practice","Technical follow-up practice","4 recorded mock interviews","Individual improvement scorecard"].map(x=><span key={x}>✓ {x}</span>)}</div></div></section>
  <section className="career"><article><h3>Latest Hiring <b>NEW</b></h3><div><strong>CAREER<br/>OPPORTUNITIES</strong><p>Curated junior SAP data roles and practical preparation guidance.</p><small>DEMONSTRATION CONTENT</small></div></article><article className="placed"><h3>Learner Milestones</h3><div><span>AK</span><section><small>CAPSTONE COMPLETE</small><strong>PROJECT<br/>SHOWCASE READY</strong><p>Built a governed sales analytics data product from source to dashboard.</p></section></div></article><article><h3>Upcoming Cohort <b>NEW</b></h3><div><strong>ENROLLMENT<br/>NOW OPEN</strong><p>Live guided classes, weekly labs, and mentor reviews.</p><small>LIMITED COHORT SIZE</small></div></article></section>
  <section className="features" id="benefits">{[["▣","Live classes","Industry use cases and expert guidance"],["✓","Assessments","Daily practice and weekly evaluation"],["◎","Projects","Testing, deployment, and portfolio work"],["♙","Interviews","Mock interviews and architecture questions"],["▤","Resume","Skills-first profile and project evidence"],["✦","Career support","Role discovery and learning roadmap"]].map((x,i)=><article className={i%2?"red":"gold"} key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section>
  <section className="voice"><div><h2>Our Success Mantra</h2>{[["Commitment","Quality training every day"],["Fulfillment","Confident learning outcomes"],["Accomplishment","Demonstrable industry skills"]].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div><div className="phones"><h2>Our Learner Voice</h2>{["Modeling Lab","Project Mentor","Study Group","Career Coach","Analytics Lab"].map((x,i)=><article style={{"--i":i} as React.CSSProperties} key={x}><b>{x}</b><p>{i%2?"Your project review is ready.":"I completed the lab today!"}</p><small>ILLUSTRATIVE MESSAGE</small></article>)}</div><div><h2>Beyond Courses</h2><div className="support">{["24/7 Support","LinkedIn Profile","Resume Writing","Alumni Sessions","Interview Prep","Live Projects"].map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="benefit"><h2>Exclusive Program Benefits</h2><div>{["Learning Materials","Resume Workshop","Interview Preparation","Real Project Guidance"].map((x,i)=><button key={x}><small>DF ACADEMY</small><strong>{x}</strong><i>▶</i><b>0{i+1}</b></button>)}</div></section>
  <section className="team" id="faculty"><h2>Meet Our Faculty</h2><p>Dedicated instructors and industry-focused mentors</p><div>{[["AR","Ananya Rao","SAP Datasphere"],["VM","Vikram Mehta","Data Architecture"],["NS","Neha Singh","Analytics & Careers"],["RK","Rohan Kapoor","SQL & Modeling"],["IP","Isha Patel","Data Integration"],["AS","Arjun Shah","Analytics Cloud"]].map(x=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><small>SAMPLE PROFILE</small></article>)}</div></section>
  <section className="stories"><h2>Our Learners&apos; Success Stories</h2><div>{["I can finally explain semantic modeling clearly.","The capstone gave me a project I can demonstrate.","Weekly labs made Datasphere feel practical."].map((x,i)=><article key={x}><b>★★★★★</b><blockquote>“{x}”</blockquote><small>ILLUSTRATIVE LEARNER STORY · 0{i+1}</small></article>)}</div></section>
  <footer id="contact"><div className="logo"><b>DF</b><span>DataForge<small>SAP DATA ACADEMY</small></span></div><p>Train with purpose. Build with data. Create business impact.</p><div><b>CONTACT</b><a href="tel:+918882178896">+91 88821 78896</a><a href="mailto:learn@dataforge.academy">learn@dataforge.academy</a></div></footer>
  <aside className="enquire"><h3>Reach Out to Us</h3>{sent?<div><b>Thank you!</b><p>Connect your email or CRM to receive this enquiry.</p><button onClick={()=>setSent(false)}>New enquiry</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><input required placeholder="Full name"/><input required type="tel" placeholder="Phone number"/><input required placeholder="Course interest"/><button>Submit</button></form>}</aside>
  {course&&<div className="modal" onMouseDown={()=>setCourse(null)}><section onMouseDown={e=>e.stopPropagation()}><button onClick={()=>setCourse(null)}>×</button><small>SAP LEARNING PROGRAM</small><h2>{course}</h2><p>Build practical capability through guided concepts, demonstrations, labs, knowledge checks, and a portfolio-ready assignment.</p><ul><li>Live instructor-led sessions</li><li>Hands-on SAP exercises</li><li>Weekly mentor feedback</li><li>Capstone project evidence</li></ul><button className="enroll">Request enrollment</button></section></div>}
 </main>
}
